services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    runtime: nvidia  # Enable NVIDIA runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py
      - ./requirements-gpu.txt:/app/requirements.txt
      - ./research.config:/app/research.config
      - ./temp_pdf:/app/temp_pdf
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=all
    depends_on:
      - searxng
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"

  searxng:
    image: docker.io/searxng/searxng:latest
    ports:
      - "4000:8080"
    environment:
      - INSTANCE_NAME=searxng
    volumes:
      - ./searxng:/etc/searxng:rw