version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "9222:9222"  # Chrome debugging port
    volumes:
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      - ./research.config:/app/research.config
      - ./temp_pdf:/app/temp_pdf  # Mount temp_pdf directory for persistence
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - searxng
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enable access to host machine
    network_mode: "host"  # Use host network to access Chrome on host machine

  searxng:
    image: docker.io/searxng/searxng:latest
    ports:
      - "4000:8080"
    environment:
      - INSTANCE_NAME=searxng
    volumes:
      - searxng-data:/etc/searxng

volumes:
  searxng-data: