services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      - ./research.config:/app/research.config
      - ./temp_pdf:/app/temp_pdf
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - searxng
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"

  searxng:
    image: docker.io/searxng/searxng:latest
    ports:
      - "4000:8080"
    environment:
      - INSTANCE_NAME=searxng
    volumes:
      - ./searxng:/etc/searxng:rw